"""criando tabelas

Revision ID: 066c4cc173c7
Revises: 
Create Date: 2024-05-08 11:07:57.067589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066c4cc173c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidadecompetencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('competencia_geral', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidadecompetencia')
    op.drop_table('curso')
    op.drop_table('competencia')
    op.drop_table('area')
    # ### end Alembic commands ###
