"""tirando mini bio

Revision ID: 13e9783e12ed
Revises: 961354b2c489
Create Date: 2024-05-20 19:32:01.764610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13e9783e12ed'
down_revision = '961354b2c489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnico', schema=None) as batch_op:
        batch_op.drop_column('mini_bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tecnico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mini_bio', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
