"""pacie e prontu4

Revision ID: 2bbac59bacfa
Revises: 00a5ba272af9
Create Date: 2024-06-05 21:09:08.512059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2bbac59bacfa'
down_revision = '00a5ba272af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               type_=mysql.NCHAR(national=True, length=32),
               existing_nullable=True)

    with op.batch_alter_table('prontu', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['paciente_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prontu', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=32),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
