"""pacie e prontu2

Revision ID: b4c782d1abd6
Revises: 2528da8c8ff4
Create Date: 2024-06-05 21:02:15.762912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4c782d1abd6'
down_revision = '2528da8c8ff4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               type_=mysql.NCHAR(national=True, length=32),
               existing_nullable=True)

    with op.batch_alter_table('prontu', schema=None) as batch_op:
        batch_op.drop_constraint('prontu_ibfk_1', type_='foreignkey')
        batch_op.drop_column('paciente_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prontu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paciente_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('prontu_ibfk_1', 'pacie', ['paciente_id'], ['id'])

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=32),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
