"""iniciando alpha infosystem

Revision ID: bdd4ac043f3b
Revises: 
Create Date: 2024-05-15 19:49:01.829193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd4ac043f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('especialidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hora', sa.Time(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hash', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash')
    )
    op.create_table('nivel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidadecompetencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('carga_horaria', sa.Integer(), nullable=True),
    sa.Column('competencia_geral', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('fk_especialidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_especialidade_id'], ['especialidade.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('fk_nivel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_nivel_id'], ['nivel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tecnico')
    op.drop_table('medico')
    op.drop_table('unidadecompetencia')
    op.drop_table('tipo')
    op.drop_table('nivel')
    op.drop_table('log_usuario')
    op.drop_table('especialidade')
    op.drop_table('curso')
    op.drop_table('competencia')
    op.drop_table('area')
    # ### end Alembic commands ###
