"""frango no shape

Revision ID: f345b748776f
Revises: 
Create Date: 2024-06-21 11:43:34.704308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f345b748776f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formapagamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marmita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('foto', sa.String(length=70), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('fk_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=200), nullable=True),
    sa.Column('senha', sa.String(length=200), nullable=True),
    sa.Column('fk_tipo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_tipo_id'], ['tipo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_pedido', sa.Date(), nullable=True),
    sa.Column('horario', sa.Time(), nullable=True),
    sa.Column('fk_formapgto_id', sa.Integer(), nullable=True),
    sa.Column('fk_usuario_id', sa.Integer(), nullable=True),
    sa.Column('fk_marmita_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_formapgto_id'], ['formapagamento.id'], ),
    sa.ForeignKeyConstraint(['fk_marmita_id'], ['marmita.id'], ),
    sa.ForeignKeyConstraint(['fk_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('usuario')
    op.drop_table('marmita')
    op.drop_table('tipo')
    op.drop_table('item')
    op.drop_table('formapagamento')
    # ### end Alembic commands ###
