"""crieiatabelalog-tirando palavras reservadas

Revision ID: f520c93d7279
Revises: 1cc97084bdc2
Create Date: 2024-06-04 20:48:18.151755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f520c93d7279'
down_revision = '1cc97084bdc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_log', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hash_log', mysql.NCHAR(national=True, length=32), nullable=True))
        batch_op.drop_column('data')
        batch_op.drop_column('hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32), nullable=True))
        batch_op.add_column(sa.Column('data', sa.DATE(), nullable=True))
        batch_op.drop_column('hash_log')
        batch_op.drop_column('data_log')

    # ### end Alembic commands ###
