"""reformulando classe médico

Revision ID: fdc995ab431d
Revises: 944b305c699b
Create Date: 2024-06-04 21:00:14.011686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdc995ab431d'
down_revision = '944b305c699b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               type_=mysql.NCHAR(national=True, length=32),
               existing_nullable=True)

    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('senha', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cpf', sa.String(length=11), nullable=True))
        batch_op.add_column(sa.Column('crm', sa.Integer(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medico', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('crm')
        batch_op.drop_column('cpf')
        batch_op.drop_column('senha')
        batch_op.drop_column('telefone')

    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.alter_column('hash_log',
               existing_type=mysql.NCHAR(national=True, length=32),
               type_=mysql.CHAR(charset='utf8mb3', collation='utf8mb3_general_ci', length=32),
               existing_nullable=True)

    # ### end Alembic commands ###
